apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    # Mesmo nome da labels do deployment(template>metadata>labels>app)
    app: api
  ports:
  # Protocolo padrão é o TCP já.
  - protocol: TCP
    # Porta do service
    port: 80
    # Porta do Pod
    targetPort: 8080
  type: ClusterIP