apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vultr-block-storage-retain
  resources:
    requests:
      storage: 10Gi