apiVersion: batch/v1
kind: Job
metadata:
  name: roleta-job
spec:
  #Pods sendo executados ao mesmo tempo com a tarefa
  parallelism: 3
  #Limeite de vezes que pode ser executado
  backoffLimit: 20
  #Quntidade de sucessos para considerar concluida
  completions: 3
  template:
    spec:
      containers:
      - name: job
        image: kubedevio/roleta        
        args:
          - "-w"
          - "5"
          - "-c"
          - "2"
          - "-m"
          - "5"
      restartPolicy: Never
  
