apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        #Imagem que pega o nome da maquina junto ao executar uma requisição.
        image: kubedevio/api-conversao:v1-machine-name
        
    