apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: eliezer123/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        env:
        - name: Mongo__Host
          value: "mongo-service.mongodb.svc.cluster.local"
        - name: Mongo__User
          value: "root"
        - name: Mongo__Password
          value: "mongopwd"
        - name: Mongo__Port
          value: "27017"
        - name: Mongo__DataBase
          value: "admin"
